### PR TITLE
Make help width configurable

### PR DESCRIPTION
**Pull request by edgano**
Issue #159
void setUsageWidth(int value)
int getUsageWidth()

To make configurable the help width

### CODE REVIEW

**Comment by edgano** [comment]
I was trying to change the declaration of `Help.usageHelpWidth` to an instance field but the will need to change several other static methods like `join` and the `TextTable` class. Is that what you really want to do? also because there any value in doing that, since you cannot have more than usage width at time? do you agree on that?

**Comment by remkop** [comment]
Hi, thanks for taking another look. (By the way, I thought I had put some feedback in a comment here earlier but I can't find it any more. Not sure what happened.)

How about this:
Let's make the default usage width configurable with a system property (`picocli.usage.width`). That gives users the ability to change the usage width while leaving our options open on the API side of things. I hesitate to commit to a programmatic API with static methods, and using a system property instead allows us to side-step that altogether and keep code changes to a minimum.

I would like to enforce a minimum usage width of 55. If a smaller value (or a non-numeric value) is specified, we log a warning and use the minimum instead. (The reason for this minimum is that option names take up 29 characters of each line, and the option descriptions need some minimum width to keep the result looking reasonably good.)

Do you think you can add tests that verify the resulting usage message? The `CommandLineHelpTest` class has many examples. It would be great if you could also add tests for edge cases (like checking that the line wrapping still works correctly with non-default width, and checking that the validation works for invalid system property values).

**Comment by pditommaso** [comment]
> we log a warning and use the minimum instead

I don't any logging in picocli, what logging approach do you or do you want to use ?

**Comment by remkop** [comment]
There’s a small Tracer class in picocli. At decision points the parser outputs messages at DEBUG, INFO or WARN level to help users troubleshoot. See http://picocli.info/#_tracing

If the user specifies an invalid value that will be ignored, there should be a warning.

**Pull request merged**
