### PR TITLE
Add documentation about resource bundle entries for negatable options

### PR DESCRIPTION
**Pull request by vanitasvitae**
Hey,
not sure if I added this to the correct file, but I thought this line was missing from the documentation.

### CODE REVIEW

**Review by remkop — APPROVED** [review]

**Comment by remkop** [comment]
@vanitasvitae Thank you for the pull request!

I was actually not aware that this is the case (that the negative form of negatable options is the key in resource bundles). 

Can you add a unit test to demonstrate?

**Review by remkop — CHANGES_REQUESTED** [review]
Can you please add a unit test that demonstrates this behavior?

**Comment by vanitasvitae** [comment]
After opening this PR, I noticed that this is in fact only true for negatable options which are supposed to be true by default (see https://picocli.info/#_negatable_options). I think this PR needs rewording :D

**Comment by vanitasvitae** [comment]
In the end I guess the behavior for negatable options is no different than for normal options (resource entry must equal `names` value without dashes).
I guess there is no need to mention this explicitly in the documentation.

**Comment by remkop** [comment]
Okay great, thank you for the confirmation! 🙏

**Pull request closed without merging**
