### PR TITLE
Positional params completion

### PR DESCRIPTION
**Pull request by avshenuk**
Add Bash completion of positional parameters based on the position in the COMP_WORDS completion array.

Fixed issue: #468

### CODE REVIEW

**Comment by remkop** [comment]
Thanks for the PR! Let me take a look tomorrow.

**Comment by remkop** [comment]
One issue I found is that when I run the `AutoCompleteTest`, the `nestedSubcommands` test hangs and eventually dies with an OOM (stack trace below). This is probably because the default index range is `0..*` and `PositionalParamSpec.index().max` is Integer.MAX_VALUE.

```
java.lang.OutOfMemoryError
	at java.lang.AbstractStringBuilder.hugeCapacity(AbstractStringBuilder.java:161)
	at java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:155)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at picocli.AutoComplete.addPosParamIndexRef(AutoComplete.java:548)
	at picocli.AutoComplete.generateNonEnumPositionParamCompletionCandidates(AutoComplete.java:543)
	at picocli.AutoComplete.generateFunctionForCommand(AutoComplete.java:500)
	at picocli.AutoComplete.bash(AutoComplete.java:349)
	at picocli.AutoCompleteTest.nestedSubcommands(AutoCompleteTest.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
```

Would you mind adding a test with multiple positional parameters that showcases the new completion logic?

**Comment by avshenuk** [comment]
Hm, I thought `Integer.MAX_VALUE` would be just inserted as it is into the Bash script.... Why should it cause the OOM.
Alright, will add as soon as I get to my laptop :D

**Comment by avshenuk** [comment]
Ah, right. I got it... It was a completely stupid idea to insert indexes like I did.... Will fix.

**Comment by avshenuk** [comment]
@remkop I thought I fixed but the tests started failing for some reason... I'll try to fix it today/tomorrow...

**Comment by remkop** [comment]
Great, thanks! Please put a comment after you pushed so I get a notification.

**Comment by avshenuk** [comment]
@remkop Okay, so I've fixed everything I could but the last issue from CodeClimate about duplicated code is not clear to me...

Also added a test subcommand for more positional params variations + added support for multi-values.

**Comment by remkop** [comment]
Great, thank you!
I’ll take a detailed look in the next few days.

**Pull request merged**
