### PR TITLE
add description about text blocks (#1028)

### PR DESCRIPTION
**Pull request by Lyther**
Hi Remkop,
    For issue #1028 , I've added descriptions about java 15's text block in user manual in both html and adoc files.
    This may save your time of writing document.
Enderaoe

### CODE REVIEW

**Comment by remkop** [comment]
Hi @Lyther, thank you!
I was hoping to include a working example in the documentation.
Would it be possible for you to provide a working example that you have tested on Java 15?

**Comment by Lyther** [comment]
Hi @remkop 
I've added an example in description and tested under Java 15, it works fine.
The user manual would look like this now:

20.10. Text Blocks for Java 15
When writing your command line program, you can use Java 15's new feature Text Block. The text block can be used in command and option description, headers and footers.

`@Option(name = { "-v", "--verbose" }, description = """
                                                    Verbose mode. Helpful for troubleshooting.
                                                    Multiple -v options increase the verbosity.
                                                    """) // write description in text block`

For more details, you can read [Java text blocks](https://www.infoq.com/articles/java-text-blocks/).

That's a pleasure to contribute to this awesome project.

**Comment by remkop** [comment]
Merged into master.
Thank you for the contribution!
I will update the release-notes later.

**Comment by remkop** [comment]
FYI:
https://twitter.com/picocli/status/1258371028876582912
Thanks!

**Pull request merged**
