### PR TITLE
CommandLine cleanup

### PR DESCRIPTION
**Pull request by rgoldberg**
Minor cleanup in `CommandLine`

### CODE REVIEW

**Comment by remkop** [comment]
The tests may be failing because of another PR I merger earlier today... need to take a look.

**Comment by rgoldberg** [comment]
The build failure does come from that PR, and is in `master`.

**Review by remkop — APPROVED** [review]

**Comment by remkop** [comment]
I ignored the failing test now.

**Comment by rgoldberg** [comment]
Thanks

**Comment by rgoldberg** [comment]
Are you waiting to merge until the build error is fixed?

**Comment by remkop** [comment]
Just caught up with other stuff. I hope to merge and do a release later today.

**Comment by rgoldberg** [comment]
Cool.  No rush, just wanted to ensure that I didn't need to make any mode modifications

**Comment by rgoldberg** [comment]
Just submitted a gradle bump to 7.4 PR.

**Pull request merged**
