### PR TITLE
WIP: Documentation: online execution of sample apps

### PR DESCRIPTION
**Pull request by deining**
Now that we have a few samples included in the documentation, I had the idea to implement online execution of these samples.
I found the JDoodle Java [online compiler](https://www.jdoodle.com/online-java-compiler/) and liked it. Embedding the online executable code sample inside the quick guide was a matter of adding two lines (see patch attached).
I now want to hear your opinion on this feature, I'm curious what you think.

**Side note:** it may not be possible to take over the current samples as is:
* Checkum.java calculates the checksum of a file, which makes it difficult/impossible to run the sampe in JDoodle,
* ASCIIArt.java calls an external server for generation of ASCII art and it seems like JDoodle prevents calls to external servers.

### CODE REVIEW

**Comment by remkop** [comment]
Very interesting! I was not aware of this.
It is a good idea to have an additional example that can be executed online, like you did in this PR.

At work, my internet access is severely limited (as in many financial institutions), and I am guessing the JDoodle example will not be visible from my work PC. I will check remotely on Monday.
My point is that this should be _supplimentary_, while the main code examples should be embedded in the documentation.
This is exactly what your PR is doing, so that is great! I will merge this soon.

**Comment by deining** [comment]
> Very interesting! I was not aware of this.
> It is a good idea to have an additional example that can be executed online, like you did in this PR.

Glad to see that you like the idea.

> At work, my internet access is severely limited (as in many financial institutions), and I am guessing the JDoodle example will not be visible from my work PC. I will check remotely on Monday.

JDoodle offers two kind of links that can be shared:

URL: https://www.jdoodle.com/a/2mxo
Embed URL: https://www.jdoodle.com/embed/v0/2mxo

I tend to use/link to the embed URL.

> My point is that this should be _supplimentary_, while the main code examples should be embedded in the documentation.

I fully agree.

> This is exactly what your PR is doing, so that is great! I will merge this soon.

Please note that my PR is work in progress. Stay tuned, I plan to work on this soon. I will back back to you once its ready for merging. In the meantime, comments are very welcome.

**Comment by remkop** [comment]
I see. I was about to merge this, but now I’ll hold off until you give the go-ahead. 

I will push some changes related to your previous PR soon, you may need to rebase.

**Comment by remkop** [comment]
I pushed my changes; please go ahead and rebase at your leisure.

**Comment by deining** [comment]
Superseded by #1196.

**Pull request closed without merging**
