### PR TITLE
Add tests for methods modified in #997

### PR DESCRIPTION
**Pull request by licia-tia**

### CODE REVIEW

**Comment by licia-tia** [comment]
Sorry I'm not quite familiar with pull requests.

**Comment by remkop** [comment]
Hi @licia-tia, thank you for the pull request!

The comment for your last commit says "DO NOT MERGE" but everything looks okay to me.
I am happy to merge this into master.
Can I go ahead?

**Comment by licia-tia** [comment]
We were doing a course project and our teacher asked us to test every method modified. I thought code modified by remkop#1033 was covered by other tests and tests I added may not help, so I added: "DO NOT MERGE" to the commit. It's surely ok if you think those were helpful!

**Comment by licia-tia** [comment]
"Add tests for #1033" is actually for #1002, I made a wrong commit message.  :-(

**Comment by remkop** [comment]
@licia-tia no worries! :-) 
Thank you for the pull request! I merged it into master. 👍 

Please also thank your teacher for me. Is your teacher @Wycers?

**Comment by Wycers** [comment]
Nooo😂 I'm also a student in the same course. And I'm in the same group as @licia-tia

**Comment by remkop** [comment]
Please thank your teacher for me!  🙇 
It is very nice to get so many helpful pull requests!

**Comment by Wycers** [comment]
LOL, I will. @NewbieOrange @jerrylususu @Hannnnnn @Linyer-qwq are also my partners. Surprise! :laughing:

**Comment by remkop** [comment]
Well, @NewbieOrange @jerrylususu @Hannnnnn @Linyer-qwq @Lyther @licia-tia @Wycers and your teacher: I think you are all awesome! 🥇 👍 🥰

**Pull request merged**
