### PR TITLE
Update option rendering (fixes #1886)

### LINKED ISSUE #1886: AsciiDoc generator doesn't output any options if all options are in ArgGroups
The AsciiDoc generator doesn't output any options for commands that have all their options defined in ArgGroups. Culprit is this piece of code:
```java
        List<ArgGroupSpec> groups = optionListGroups(spec);
        for (ArgGroupSpec group : groups) { options.removeAll(group.allOptionsNested()); }
        
        if (options.isEmpty() && !spec.usageMessage().showEndOfOptionsDelimiterInUsageHelp()) {
            pw.printf("// tag::picocli-generated-man-section-options[]%n");
            pw.printf("// end::picocli-generated-man-section-options[]%n");
            pw.println();
            return;
        }
```

If all options are contained in ArgGroups, then `options` will be empty, and due to the `return` statement in the code above, the code to output ArgGroup options is skipped:

```java
        // now create a custom option section for each arg group that has a heading
        Collections.sort(groups, new SortByOrder<ArgGroupSpec>());
        for (ArgGroupSpec group : groups) {
            pw.println();
            String heading = makeHeading(group.heading(), "Options Group");
            pw.printf("== %s%n", COLOR_SCHEME.text(heading));
        ...
```

I'll look at submitting a PR, but any suggestions on how to best fix this are welcome.

### PR DESCRIPTION
**Pull request by rsenden**

### CODE REVIEW

**Review by remkop — APPROVED** [review]

**Comment by remkop** [comment]
Merged. Thank you for the contribution!

**Comment by remkop** [comment]
Hi @rsenden, while looking at fixing the CI/CD pipeline (https://github.com/remkop/picocli/issues/1930), I noted that `ManPageGeneratorTest` now has 3 failing tests (testEndOfOptionsWithoutOptions -  line 307, testNamelessCommand line 489 and testHiddenOptions line 242). I believe this is related to the changes for this PR.

Can I ask you to take a look at these test failures? 😅

**Comment by wtfacoconut** [comment]
Hey @remkop, @rsenden has asked me to have a look at the tests that you pointed out. I've just now started looking things, but it's a bit late where I'm at. I'll try to produce something to address the failing tests in next day. Is that okay with you?

**Comment by remkop** [comment]
Sure no problem! Thank you for helping out!

**Comment by remkop** [comment]
@wtfacoconut Did you have a chance to look at this? 
I am thinking to do a 4.7.1 release in the next few days, would be great to include your tests. 😅

**Comment by wtfacoconut** [comment]
@remkop . Sorry for the delay. Some family matters came up yesterday. I'll respond back with a few questions/comments in issue #1930 .

**Comment by remkop** [comment]
No worries! Family first! 😊

**Pull request merged**
