### PR TITLE
Java examples for #223.

### PR DESCRIPTION
**Pull request by RobertZenz**
This is supposed to be a preview of how the usage examples I'm going to write will look like, so no merge is requested at this point. Just let me know if the style is okay like this or if you'd like to have them differently.

I'll add more later, of course and update this pull request until I'm done.

### CODE REVIEW

**Comment by remkop** [comment]
Thanks for working on this! Generally looks great!

I think it would be a good idea for all examples to show error handling for invalid input. (Like, when a non-existing an option is specified.) What do you think?

Also, could the package for the examples be `picocli.examples`? If the example class is viewed in isolation it's nice if the package name still shows the intention.

**Comment by aadrian** [comment]
> I think it would be a good idea for all examples to show error handling for invalid input.

+1 .
Would be really useful for the examples to show best practices as much as possible.

**Comment by remkop** [comment]
The directory structure `examples/src/main/java/picocli/examples` is now pushed to master.

I put some initial Groovy examples in `examples/src/main/groovy/picocli/examples`. These are meant to be used in a DZone article I'm working on. I wanted to keep these scripts very short, hence the lack of javadoc or groovydoc...

**Comment by RobertZenz** [comment]
I've updated the examples, added error handling and moved them to the examples package. I just realized that another example for when help is requested is missing, I will add that later.

**Comment by remkop** [comment]
This is great! 
Can you rename Unnamed Parameters to Positional Parameters to be consistent with the user manual?
Add yourself as an `@author` in the javadoc, and it’s ready to merge I think.

**Comment by remkop** [comment]
Would you mind prefixing the class names these examples with `Populate`? 

I’m thinking later we’ll probably also have examples for the `CommandLine::parse` method, and for the `run`, `call` and `parseWithHandlers` convenience methods. 

Class names may help users quickly find examples relevant for their needs.

**Comment by RobertZenz** [comment]
I've renamed the classes, added myself as author and also renamed the example for the positional parameters. Also there is now a simple example for printing the usage/help (though, a little bit redundant because I already do that in all examples, but still) and mostly spelling fixes are in it.

**Pull request merged**
