### PR TITLE
DOC: Fix PrintExceptionMessageHandler example

### PR DESCRIPTION
**Pull request by hosmanadam**

### CODE REVIEW

**Comment by remkop** [comment]
@hosmanadam Thanks for the PR!

The `index.html` file is generated from the `index.adoc` file. We should fix the `index.adoc` file too or your changes will be overwritten the next time index.html is generated.

To test, run:

```
gradlew ascii
```

Then check the generated HTML  in build/docs/html5/index.html
Thanks again for helping to make picocli a better library!

**Comment by hosmanadam** [comment]
@remkop Thanks for the heads up, I made that change as well.
Least I can do, thanks for an awesome tool :)

**Comment by remkop** [comment]
Merged and updated release notes.
Thank you again for the contribution!

Can I ask:

* what is it that you like about picocli?
* what would you do if picocli did not exist?

**Comment by hosmanadam** [comment]
@remkop Sure. I like that it works well and is conveniently annotation-configured, which is a familiar workflow when you come from Spring. If it didn't exist, I'd build our CLI in [Click](https://click.palletsprojects.com/) instead, but then no one else on the team could touch it, because they're Java guys.

**Comment by remkop** [comment]
Thank you!

Enjoy picocli! 😉

**Pull request merged**
