### PR TITLE
Subcommand suggestions

### PR DESCRIPTION
**Pull request by mauvo**
Re: https://github.com/remkop/picocli/issues/2026

### CODE REVIEW

**Review by remkop — DISMISSED** [review]
Looks good, thank you!

**Comment by remkop** [comment]
I do see one failing test:

```
picocli.UnmatchedArgumentExceptionTest > testUnmatchedArgumentSuggestsSubcommands FAILED
    org.junit.ComparisonFailure at UnmatchedArgumentExceptionTest.java:84
```

Can you take a look?

**Comment by mauvo** [comment]
Ah yes, I didn't understand the test framework's results. Anyway, it should be fixed now.

**Review by remkop — APPROVED** [review]

**Comment by remkop** [comment]
Merged. 
Thank you for the contribution!

**Pull request merged**
