### PR TITLE
Fixes #665 - invoking a method with a @Command annotation uses specified factory

### LINKED ISSUE #665: Invoking a method with a @Command annotation doesn't use specified factory
Invoking a method with a @Command annotation doesn't use specified factory.

### PR DESCRIPTION
**Pull request by sualeh**

### CODE REVIEW

**Comment by remkop** [comment]
Awesome, thanks!

I eyeballed the changes and it looks good, but the Tracis CI build is failing. 

Looks like this test: `CommandLineCommandMethodTest.testCommandMethodsRequireNonArgConstructor` fails. 
However, with your changes this test may no longer be valid. Can you take a look?

**Comment by sualeh** [comment]
I have fixed `CommandLineCommandMethodTest.testCommandMethodsRequireNonArgConstructor`. Will start a new build soon.

**Comment by sualeh** [comment]
@remkop - I think this is ready to merge.

**Comment by remkop** [comment]
Merged into master. 
Thank you for the contribution!

**Pull request merged**
