### PR TITLE
[#1388] Fix subcommand aliases autocomplete regression

### LINKED ISSUE #1388: 4.3.2->4.6.1 regression, incorrect autocompletion is generated for subcommand aliases, because of which autocomplete does not work for subcommand specified by alias.
TLDR autocompletion does not work for aliases.

Command defined as:

```
@CommandLine.Command(description = "Receive avro messages from kafka",
        usageHelpWidth = 120,
        name = "receive-avro-from-kafka",
        aliases = {"rafk"})
public class ReceiveAvroMessagesFromKafka extends JsonLikeKafkaMessageReceiver implements Callable<Integer> {
```

will generate autocompletion:

```
function _complete_campTools() {
...
  local cmds4=(receive-avro-from-kafka)
  local cmds5=(receive-avro-from-kafka)
...  
  if CompWordsContainsArray "${cmds5[@]}"; then _picocli_campTools_rafk; return $?; fi
  if CompWordsContainsArray "${cmds4[@]}"; then _picocli_campTools_receiveavrofromkafka; return $?; fi
...
```

_complete_campTools() is top level function. My interpretation is, that cmds4 and cmds5 are generated duplicated. Both subcomand autocomplete functions are equal, but we test presence of wrong word in COMP_WORDS array, meaning that we cannot ever call rafk alias related function. Fixing it to `local cmds5=(rafk)` fixes the issue and autocomplete works again.

Not sure if that's enough to find the issue, or whether some sub-standard coding on my part causes that. If you need smth more, I can help / share project.

### PR DESCRIPTION
**Pull request by NewbieOrange**
This seems to fix #1388 regression, and I have added a new test for the issue.

However, this cause #1352 `testIssue1352_SubcommandNameResourceBundle` to fail, which seemed to be caused by `descriptor.commandName` is `${project.cli.command}`, and it's from `commandLine.getSubcommands().entrySet().?.getKey()`, indicating there might be some issue in resource bundle propagation for subcommands.

@remkop any thoughts?

### CODE REVIEW

**Comment by NewbieOrange** [comment]
By adding a workaround in `createSubHierarchy(String scriptName, CommandLine commandLine, List<CommandDescriptor> out)` I can get `testIssue1352_SubcommandNameResourceBundle` to pass, but it is a weird solution.

```java
private static void createSubHierarchy(String scriptName, CommandLine commandLine, List<CommandDescriptor> out) {
// ...
    String commandName = entry.getKey(); // may be an alias
    if (commandName.startsWith("$")) {
        commandName = spec.resourceBundle().getString(commandName.substring(2, commandName.length() - 1));
    }
// ...
}
```

**Comment by NewbieOrange** [comment]
The subcommands now get their name inerpolated in `addSubcommand()`, fixing #1352 test regression.

Not sure it is the correct solution - but all tests now pass.

**Comment by NewbieOrange** [comment]
Still need some changes, not ready for merge yet.

**Comment by remkop** [comment]
> Still need some changes, not ready for merge yet.

Okay, understood. Thank you for looking at this!

**Comment by NewbieOrange** [comment]
> Okay, understood. Thank you for looking at this!

Fixed the issue now.

**Comment by remkop** [comment]
Apologies for the long wait. I will try to look at this soon!

**Pull request merged**
