### PR TITLE
Issue #2074 AutoComplete with jline3 is showing hidden values

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
This fixed my issue on the artemis shell / jline3 integration. I'm not sure yet how to add a test for this (still looking) meanwhile this serves as a discussion starter.

**Comment by clebertsuconic** [comment]
@remkop I tried to write a test :) .. but I don't understand how this dejavu test works, and what you expect on these spawned tests.

I supposed they are emulating an auto-completion and terminal .. but I couldn't progress much further without some guidance.

It seems though this should be an easy fix for someone knowledgeable about this codebase.. if you could handle this issue.. or someone else already knowledgeable here?

**Comment by remkop** [comment]
@clebertsuconic Thanks for raising this and thanks for the pull request!

Looks good. 
I’m on my phone now and want to take another look on my pc before merging it. 

About the tests, the dejagnu stuff is mostly for testing bash completion and it’s a bit of a learning curve…
I haven’t considered using it to test the JLine stuff, that’s an interesting idea. But your change is straightforward enough.

**Comment by clebertsuconic** [comment]
@remkop how often you make releases? just planning the artemis release after this. (I could also extend and fix in the usage for now).. just for my planning.

thanks.

**Review by remkop — APPROVED** [review]

**Comment by remkop** [comment]
Merged. Thank you for the contribution!

**Comment by clebertsuconic** [comment]
@remkop thank you so much.

I hate to be one of those guys asking for a release? :)  but how far is a release? :)

**Comment by remkop** [comment]
I will probably try to fix some more items that are currently [in scope for 4.7.5](https://github.com/remkop/picocli/milestone/83) before doing a release. I don't have time lines, sorry.

**Pull request merged**
