### PR TITLE
Add tests for #803

### PR DESCRIPTION
**Pull request by byteit101**
As requested, some tests for #803. Can't get them to work locally for some reason though, as I commented in #803

### CODE REVIEW

**Comment by remkop** [comment]
Thank you! Taking a look now...

**Comment by remkop** [comment]
The test helped me quickly zoom in to the cause of the problem (thanks again): the logic to pick up this attribute wasn’t implemented yet in the annotation processor.  Working on this now.

**Comment by remkop** [comment]
I pushed a fix for #803 to master. 
Can you verify?

**Comment by byteit101** [comment]
I have verified that everything works. Thanks!

**Comment by remkop** [comment]
Great!
If you like the project please star it on GitHub and tell your friends! ;-)

**Pull request merged**
